---
- name: Pull the image in production host and create the container
  hosts: all
  tasks:
    - name: Pulling the Image
      docker_image:
        name: ashuj3112/calcdockerimage
        source: pull